server:
  port: 8082


spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/login?serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: G9vL!dX3y7@rWqz!kBp#NfTz*QvXeRgU1JxL0sYw!HtRuBvMzKsFtWuZoQjLrNdX
  access-exp: 3600000     # 30min
  refresh-exp: 1209600000  # 2week
